backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"
site_url: https://www.olumal.com
collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "id"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "relation", collection: "categories", searchFields: ["name"], displayFields: ["name"], valueField: "id", multiple: true}
      - {label: "Author", name: "author", widget: "string", default: "Malintha Custer"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "categories"
    label: "Categories"
    folder: "categories"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - {label: "ID", name: "id", widget: "id"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}